<?xml version="1.0" encoding="ISO-8859-1"?>
<definitions xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:cuenta" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:cuenta">
<types>
<xsd:schema targetNamespace="urn:cuenta"
>
 <xsd:import namespace="http://schemas.xmlsoap.org/soap/encoding/" />
 <xsd:import namespace="http://schemas.xmlsoap.org/wsdl/" />
</xsd:schema>
</types>
<message name="totalRequest">
  <part name="cantidad" type="xsd:float" />
  <part name="precio" type="xsd:float" /></message>
<message name="totalResponse">
  <part name="return" type="xsd:float" /></message>
<portType name="miservicioPortType">
  <operation name="total">
    <input message="tns:totalRequest"/>
    <output message="tns:totalResponse"/>
  </operation>
</portType>
<binding name="miservicioBinding" type="tns:miservicioPortType">
  <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  <operation name="total">
    <soap:operation soapAction="urn:cuenta#total" style="rpc"/>
    <input><soap:body use="encoded" namespace="urn:cuenta" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></input>
    <output><soap:body use="encoded" namespace="urn:cuenta" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/></output>
  </operation>
</binding>
<service name="miservicio">
  <port name="miservicioPort" binding="tns:miservicioBinding">
    <soap:address location="http://localhost/mozovirtual/SOAP/servicio.php"/>
  </port>
</service>
</definitions>